server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jrtp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: emailinspringboot@gmail.com 
    password: vgdnowlugqilpapm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com      

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER        